##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/belz6267/public_html/bellawan.my.id
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R milestone $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
